FROM node:22 AS build

WORKDIR /app

COPY package*.json ./
RUN npm ci

COPY . .
RUN node ./node_modules/@angular/cli/bin/ng.js build --configuration production

FROM nginx:alpine

COPY --from=build /app/dist/visordocs-frontend/browser /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]